<center>

# **Scratch GPT**

---

## Daniel Sbeiti

---

### **Dataset Visualization**

In [2]:
!curl -o input.txt https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1089k  100 1089k    0     0  5407k      0 --:--:-- --:--:-- --:--:-- 5419k


In [7]:
with open('elonx.txt', 'r', encoding='utf-8') as f:
    text = f.read()


print('First 500 characters of the dataset:')
print(text[:1000])

First 500 characters of the dataset:
@BillyM2k I find the gold toe sock – inevitably off kilter &amp; washed out – a little troubling esthetically &amp; arguably a bit corpo

Sock Con, the conference for socks

Always something new for the magazine cover and the articles practically write themselves

@ExplainThisBob This guy gets it

Sock tech is so advanced that you can get pretty much anything in sock form these days!

I must confess to a penchant for creative socks

@slashdot It’s time

@TonyadeVitti @historydefined His success was in fact due, in part, because he was super fun at parties, spoke and wrote incredibly well!

@historydefined While bleak posts maybe generate more clicks, more happier moments in history would be nice

@mishaboar @boringcompany Supporting Doge wherever possible

Moon brought us together in ‘69,
Mars can do that in the future

Without a common goal, 
humanity will fight itself

@PPathole Exactly

@AlexBerenson @Twitter Can you say more about this: “… press

##### **Character Level Vocabulary** 

In [8]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

print('Length of dataset in characters:', len(text))
print('Number of unique characters:', vocab_size)
print('Unique characters:', ''.join(chars))

Length of dataset in characters: 414840
Number of unique characters: 218
Unique characters: 
 !"#$%&'()*+,-./0123456789:;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyz{|}~ àéō‍–‘’“”…≠☺♂♥⚡❤⬇始皇秦️🇦🇪🇫🇮🇯🇲🇳🇴🇵🇷🇸🇺🌶🌹🍀🍆🍩🍳🍷🍻🍿🎂🎣🎯🎱🎶🏆🐈🐝🐥🐰🐹👀👅👏👑👖👶👽💕💗💙💛💥💦💨💩💪💫💯💰📜🔁🔥🖤😀😂😃😈😉😊😋😎😑😔😜😢😭😮😳😴🙄🙌🙏🚀🚃🚽🛌🛰🛸🤔🤖🤗🤞🤣🤦🤩🤭🤯🤷🥁🥜🥰🥲🥹🦇🧀🧌🧐🧠🧵🩸🪶🫐🫡🫶


##### **Encoder-Decooder**

In [5]:
## Mapping characters to integers and vice versa
stoi = { ch: i for i, ch in enumerate(chars) }
itos = { i: ch for i, ch in enumerate(chars) }
print('Mapping of characters to indices:', stoi)


# Encode the text into integers
def encode(s):
    return [stoi[c] for c in s]

# Decode the integers back into text
def decode(l):
    return ''.join([itos[i] for i in l])

print('\nEncoding example:')
print(encode('Hello, World!'))
print('\nDecoding example:')
print(decode(encode('Hello, World!')))

Mapping of characters to indices: {'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}

Encoding example:
[20, 43, 50, 50, 53, 6, 1, 35, 53, 56, 50, 42, 2]

Decoding example:
Hello, World!


##### **We encode dataset**

In [6]:
import torch

In [7]:
data = torch.tensor(encode(text), dtype=torch.long)
print('Data shape:', data.shape)
print('Data type:', data.dtype)
print('\nFirst 100 characters of encoded data:')
print(data[:100])

Data shape: torch.Size([1115394])
Data type: torch.int64

First 100 characters of encoded data:
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


##### **Train Test split**

In [8]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]
print('Training data shape:', train_data.shape)
print('Validation data shape:', val_data.shape)

Training data shape: torch.Size([1003854])
Validation data shape: torch.Size([111540])


##### **Context concept**

In [9]:
## Defining block as context size
block_size = 8

## Example of context usage in training
print('Example of context usage:')
x = train_data[:block_size]
y = train_data[1:block_size+1]

for i in range(block_size):
    print(f'Input: {x[:i+1]}, Target: {y[i]}')


Example of context usage:
Input: tensor([18]), Target: 47
Input: tensor([18, 47]), Target: 56
Input: tensor([18, 47, 56]), Target: 57
Input: tensor([18, 47, 56, 57]), Target: 58
Input: tensor([18, 47, 56, 57, 58]), Target: 1
Input: tensor([18, 47, 56, 57, 58,  1]), Target: 15
Input: tensor([18, 47, 56, 57, 58,  1, 15]), Target: 47
Input: tensor([18, 47, 56, 57, 58,  1, 15, 47]), Target: 58


In [10]:
torch.manual_seed(1337)
batch_size = 4   ## batch sequences to be processed in parallel, we split text in 4
block_size = 8   ## context size to look at in the past

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # random starting indices
    
    # Create batches of data
    # x is the input, y is the target
    # x is the sequence of characters, y is the next character for each
    # x[i] is the input sequence, y[i] is the target sequence

    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

# Example of getting a batch
print('Example of a batch:')
xb, yb = get_batch('train')
print('\nBatch x shape:', xb.shape)
print('Batch y shape:', yb.shape)
print('\nBatch x of 4 independent sequences:')
print(xb)
print('\nBatch y associated:')
print(yb)

Example of a batch:

Batch x shape: torch.Size([4, 8])
Batch y shape: torch.Size([4, 8])

Batch x of 4 independent sequences:
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])

Batch y associated:
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


##### **Bigram LM**

In [11]:
import torch.nn as nn
import torch.nn.functional as F

In [12]:
class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        ## Embedding layer
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)


    def forward(self, idx, targets=None):

        ## Forward pass, we get scores for next characters of sequence given the input for each vocab
        logits = self.token_embedding_table(idx)   # (batch_size (B), block_size (T), vocab_size (C))

        ## Loss to know how good logits generated are close to targets
        if targets is None:
            loss = None
        
        else:
            ### Reshape logits and targets to compute loss if targets are provided
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)

            ### Compute loss cross entropy
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        ## Generate new tokens for every B dimension (batch) over time (T) for max_new_tokens
        ## idx is the input sequence, we will append new tokens to it
        ## idx shape: (B, T)

        for _ in range(max_new_tokens):
            ### get the logits for the next character
            logits, _ = self(idx)       # logits shape: (B, T, C)

            ### Focus on the last time step
            logits = logits[:, -1, :]   # logits shape: (B, C)

            ### Apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1)  # probs shape: (B, C)

            ### Sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1)  # idx_next shape: (B, 1) (1 pred for each batch)

            ### Append the new token to the input sequence
            idx = torch.cat((idx, idx_next), dim=1)

        return idx
    


### Example
model = BigramLanguageModel(vocab_size)

print('\nExample forward pass:')
out, loss = model(xb, yb)

print('Output shape:', out.shape)
print('Loss value:', loss.item())

### Example of generation, we give it a 0 which is coding for new line
print('\nExample generation:')
print('Input sequence:', decode([0]))
print('Generated sequence:')
print(decode(model.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))



Example forward pass:
Output shape: torch.Size([32, 65])
Loss value: 5.036386013031006

Example generation:
Input sequence: 

Generated sequence:

lfJeukRuaRJKXAYtXzfJ:HEPiu--sDioi;ILCo3pHNTmDwJsfheKRxZCFs
lZJ XQc?:s:HEzEnXalEPklcPU cL'DpdLCafBheH


##### **Training of model**

In [13]:
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

In [14]:
batch_size = 32

for step in range(10000):
    xb, yb = get_batch('train')      # get a batch of data
    logits, loss = model(xb, yb)     # forward pass, get logitys and loss

    optimizer.zero_grad(set_to_none=True)   # zero the gradients
    loss.backward()                         # backward pass, compute gradients
    optimizer.step()                        # update the weights

    if step % 1000 == 0:
        print(f'Step {step}, Loss: {loss.item()}')

Step 0, Loss: 4.647705078125
Step 1000, Loss: 3.664973020553589
Step 2000, Loss: 3.3166022300720215
Step 3000, Loss: 2.8780226707458496
Step 4000, Loss: 2.6928253173828125
Step 5000, Loss: 2.4840328693389893
Step 6000, Loss: 2.504540205001831
Step 7000, Loss: 2.510176658630371
Step 8000, Loss: 2.409280776977539
Step 9000, Loss: 2.4302585124969482


In [15]:

print('\nFinal generation:')
print('Input sequence:', decode([0]))
print('Generated sequence:')
print(decode(model.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=300)[0].tolist()))


Final generation:
Input sequence: 

Generated sequence:

M:
IUSh t,
F th he d ke alved.
Thupld, cipbll t
I: ir w, l me sie hend lor ito'l an e

I:
Gochosen ea ar btamandd halind
Aust, plt t wadyotl
I bel qunganonoth he m he de avellis k'l, tond soran:

WI he toust are bot g e n t s d je hid t his IAces I my ig t
Ril'swoll e pupat inouleacends-athiqu heame


<br>

### **Self Attention**

In [31]:
torch.manual_seed(1337)
B, T, C = 4, 8, vocab_size
x = torch.randn(B, T, C)


### One head of SA
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

k = key(x)   # (B, T, head_size)
q = query(x) # (B, T, head_size)
v = value(x) # (B, T, head_size)

### Attention scores
wei = q @ k.transpose(-2, -1)  # (B, T, head_size) @ (B, head_size, T) -> (B, T, T)


### Attention mask
tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
print('\nMasked weights example batch:')
print(wei[0])


Masked weights example batch:
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2174, 0.7826, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0876, 0.8928, 0.0195, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0564, 0.7278, 0.0292, 0.1866, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2825, 0.1124, 0.0626, 0.5385, 0.0040, 0.0000, 0.0000, 0.0000],
        [0.0052, 0.4463, 0.0116, 0.2922, 0.0121, 0.2326, 0.0000, 0.0000],
        [0.6334, 0.0123, 0.0444, 0.1499, 0.0048, 0.1514, 0.0038, 0.0000],
        [0.0271, 0.1895, 0.0454, 0.0469, 0.1161, 0.0911, 0.0329, 0.4510]],
       grad_fn=<SelectBackward0>)


In [33]:
out = wei @ v

print('\nOutput of one head of self-attention:')
print(out.shape)
print("\nOutput of one head of self-attention for first batch:")
print(out[0])


Output of one head of self-attention:
torch.Size([4, 8, 16])

Output of one head of self-attention for first batch:
tensor([[-8.2172e-01,  4.7129e-01,  5.8801e-02, -4.4999e-01,  5.2736e-01,
         -8.4573e-01,  1.4697e-04, -4.8940e-01, -4.9378e-01, -2.8120e-01,
         -5.4854e-01, -1.0617e-01,  1.4664e+00, -1.9969e-01,  4.4788e-01,
         -3.1392e-01],
        [-4.0749e-01,  8.1118e-02,  4.6230e-01,  4.9075e-01,  1.3289e-01,
          6.8089e-01,  3.6334e-01,  3.1203e-01,  2.2027e-01, -3.6878e-01,
         -1.6352e-01,  3.0710e-01,  7.1388e-01, -2.2744e-01, -2.9124e-02,
         -7.3181e-01],
        [-3.3474e-01,  4.2210e-02,  5.1649e-01,  6.0874e-01,  8.0613e-02,
          9.1590e-01,  4.2155e-01,  4.3073e-01,  3.3944e-01, -3.7708e-01,
         -8.2194e-02,  3.6995e-01,  5.8980e-01, -2.2084e-01, -1.1997e-01,
         -8.0739e-01],
        [-2.2626e-01,  5.5309e-02,  4.3217e-01,  5.8852e-01,  6.1528e-02,
          7.6804e-01,  4.0485e-01,  4.8535e-01,  3.0600e-01, -1.1146e-01,


<br>

### **Tokenization**